require("user.options")
require("user.lazy")
require("user.keymaps")
require("user.highlight_yank")
require("user.format_on_save")
require("user.edit_text")
require("user.utils")
require("user.resize_windows")
